# Generated by Django 5.0.6 on 2024-07-18 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.domain'),
        ),
    ]
