# Generated by Django 5.0.6 on 2024-07-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_domain_alter_skill_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='domain',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
